# Generated by Django 5.0 on 2024-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=1000, unique=True),
        ),
    ]
