# Generated by Django 5.0 on 2024-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0004_user_is_profile_set"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workerprofile",
            old_name="nic",
            new_name="cnic_back",
        ),
        migrations.AddField(
            model_name="user",
            name="cnic",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="about",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="cnic_front",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="experience",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="profession",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
