# Generated by Django 5.0 on 2024-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0005_rename_nic_workerprofile_cnic_back_user_cnic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
