# Generated by Django 5.0 on 2024-03-26 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0006_user_address_user_phone"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkerProfile",
            new_name="WorkerProfileModel",
        ),
    ]
