# Generated by Django 5.0 on 2024-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0007_rename_workerprofile_workerprofilemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_declined",
            field=models.BooleanField(default=False),
        ),
    ]
