# Generated by Django 5.0 on 2024-04-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0010_job_jobimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
