# Generated by Django 5.0 on 2024-04-25 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0011_user_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofilemodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
