# Generated by Django 5.0 on 2024-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0013_alter_workerprofilemodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.FloatField(default=5),
        ),
    ]
