# Generated by Django 5.0 on 2024-04-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0014_user_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="rating",
        ),
        migrations.AddField(
            model_name="workerprofilemodel",
            name="count_projects",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workerprofilemodel",
            name="rating",
            field=models.FloatField(default=5),
        ),
    ]
