# Generated by Django 5.0 on 2024-04-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appsrc",
            "0015_remove_user_rating_workerprofilemodel_count_projects_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NewQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=1000)),
                ("email", models.CharField(max_length=1000)),
                ("description", models.CharField(max_length=1000)),
                ("project_name", models.CharField(max_length=1000)),
                ("location", models.CharField(max_length=1000)),
                ("budget", models.CharField(max_length=1000)),
                ("category", models.CharField(max_length=1000)),
            ],
        ),
    ]
