# Generated by Django 5.0 on 2024-04-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0016_newquote"),
    ]

    operations = [
        migrations.AddField(
            model_name="newquote",
            name="order_placed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newquote",
            name="quotes",
            field=models.IntegerField(default=0),
        ),
    ]
