# Generated by Django 5.0 on 2024-04-28 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0017_newquote_order_placed_newquote_quotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="newquote",
            name="date_placed",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
