# Generated by Django 5.0 on 2024-04-30 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0019_chatroom_model_user_message_userroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_amount", models.CharField(max_length=100)),
                ("bid_estimated_time", models.CharField(max_length=100)),
                ("bid_description", models.CharField(max_length=100)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="appsrc.newquote",
                    ),
                ),
            ],
        ),
    ]
