# Generated by Django 5.0 on 2024-04-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0021_bid_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="status",
            field=models.CharField(default="Sent", max_length=1000),
        ),
    ]
