# Generated by Django 5.0 on 2024-05-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0023_bid_accepted_bid_declined"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("payment_verified", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("TID", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "receipt",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("completed", models.BooleanField(default=False)),
                ("rating", models.FloatField(null=True)),
                ("feedback", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="appsrc.bid",
                    ),
                ),
            ],
        ),
    ]
