# Generated by Django 5.0 on 2024-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0026_order_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
