# Generated by Django 5.0 on 2024-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0029_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="client_name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
