# Generated by Django 5.0 on 2024-05-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0030_feedback_client_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("subtitle", models.CharField(max_length=15000)),
                ("heading1", models.CharField(blank=True, max_length=15000, null=True)),
                ("heading2", models.CharField(blank=True, max_length=15000, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=50000, null=True),
                ),
                (
                    "first_para",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "second_para",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "third_para",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("list1", models.CharField(blank=True, max_length=50000, null=True)),
                ("list2", models.CharField(blank=True, max_length=50000, null=True)),
                ("author", models.CharField(blank=True, max_length=30, null=True)),
                ("image", models.ImageField(upload_to="images/")),
                ("image2", models.ImageField(null=True, upload_to="images/")),
                ("date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("reviewer", models.CharField(blank=True, max_length=30, null=True)),
                ("review", models.CharField(blank=True, max_length=300, null=True)),
                ("video_url", models.CharField(blank=True, max_length=200, null=True)),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
            ],
        ),
    ]
